### PR TITLE
Adding support for User Milestones

### PR DESCRIPTION
**Pull request by stjohnjohnson**
https://github.com/DonorDrive/PublicAPI/blob/master/resources/milestones.md

Local test:
```bash
$ npm run demo
> extra-life-api@7.2.0 demo
> npm run build && node dist/demo.js


> extra-life-api@7.2.0 build
> npm run clean && npm run lint && echo Using TypeScript && tsc --version && tsc --pretty


> extra-life-api@7.2.0 clean
> rimraf lib


> extra-life-api@7.2.0 lint
> tslint --force --format verbose "src/**/*.ts"

Using TypeScript
Version 3.9.10
{
  countMilestones: '2',
  countPages: 1,
  milestones: [
    {
      fundraisingGoal: 4752.66,
      description: '2020 Donation Total',
      links: [Object],
      milestoneID: '216F90CC-D9F4-803F-B89914C54151EAD8',
      isActive: true
    },
    {
      fundraisingGoal: 7116.2,
      description: '2021 Donation Total',
      links: [Object],
      milestoneID: '2161A3C4-DCED-8376-70BCB0C21A9F4462',
      isActive: true
    }
  ]
}
```

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
Additional note: I did not check in the compiled code or update the version number.  I figured I'd leave that to you.

**Comment by ammuench** [comment]
Just merged in #21, if you can resolve conflicts and address the comment I'll merge this in and publish a new version tonight/tomorrow

**Comment by stjohnjohnson** [comment]
@ammuench I cleaned up the merged code from #18 so that the formatting is consistent with the rest of the module and the arrays return in a format consistent with other array calls.  Additionally, I fixed the `countDonations` returns to come back as numbers and not strings.

**Review by ammuench — APPROVED** [review]

**Comment by ammuench** [comment]
Approved, `v8.0.0` should be live with all the updates now!

**Pull request merged**
