### PR TITLE
add badges, incentives, milestones

### PR DESCRIPTION
**Pull request by MarceloAlves**
It's me again. There were a few endpoints I need access to so I figured I might as well add them here

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
I added milestones as well in #21.  I would support merging either PRs.  There are additional optional fields in milestones as well as support for arrays (in the event you have a LOT of milestones).

**Comment by stjohnjohnson** [comment]
@ammuench would love your 👀 on this and/or #21.  It would be great to get this in before Game Day

**Comment by MarceloAlves** [comment]
This has been open for a while so yours is probably more up to date. I ended up just making my own library to use in my app/stream

**Review by ammuench — APPROVED** [review]

**Comment by ammuench** [comment]
`v8.0.0` should be live with these updates now

**Pull request merged**
